spring:
  application:
    name: product-demo

  datasource:
    url: jdbc:postgresql://localhost:5433/ecom_db
    username: postgres
    password: api@istad
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  security:
#    user:
#      name: developer
#      password: secure1122